name: My First Push
on:
  pull_request:

jobs:
  Tarea1:
    runs-on: ubuntu-22.04

    steps:
      - name: Datos del Pull Request
        run: |
          echo "Título del PR: ${{ github.event.pull_request.title }}"
          echo "Descripción: ${{ github.event.pull_request.body }}"
          echo "Rama de Origen: ${{ github.event.pull_request.head.ref }}"
          echo "Rama deDestino: ${{ github.event.pull_request.base.ref }}"
          echo "Estado del PR: ${{ github.event.pull_request.state }}"
          echo "¿Ya fue fusionado?: ${{ github.event.pull_request.merged }}"
